[package]
name = "algo"
version = "0.1.0"
authors = ["chenyukang <moorekang@gmail.com>"]
edition = "2018"


[dependencies]
clap = "3.0.0-beta.2"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
pretty_env_logger = "0.4"
url = "2.2.0"